# Traefik dynamic configuration for enhanced security

# TLS configuration
tls:
  options:
    default:
      sslStrategies:
        - "tls.SniStrict"
      minVersion: "VersionTLS12"
      maxVersion: "VersionTLS13"
      cipherSuites:
        - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
        - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
        - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
        - "TLS_RSA_WITH_AES_256_GCM_SHA384"
        - "TLS_RSA_WITH_AES_128_GCM_SHA256"
      curvePreferences:
        - "CurveP521"
        - "CurveP384"
      alpnProtocols:
        - "h2"
        - "http/1.1"

# HTTP middleware for security
http:
  middlewares:
    # Security headers
    security-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "https"
        customResponseHeaders:
          X-Content-Type-Options: "nosniff"
          X-Frame-Options: "DENY"
          X-XSS-Protection: "1; mode=block"
          Strict-Transport-Security: "max-age=31536000; includeSubDomains; preload"
          Referrer-Policy: "strict-origin-when-cross-origin"
          Content-Security-Policy: "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self'; connect-src 'self' https://api.github.com; frame-ancestors 'none'"
          Permissions-Policy: "geolocation=(), microphone=(), camera=(), payment=(), usb=(), magnetometer=(), gyroscope=(), speaker=(), vibrate=(), fullscreen=(self), sync-xhr=()"
        accessControlAllowMethods:
          - "GET"
          - "POST"
          - "PUT"
          - "DELETE"
          - "OPTIONS"
        accessControlAllowOriginList:
          - "https://localhost:8443"
        accessControlMaxAge: 100
        addVaryHeader: true

    # Rate limiting
    rate-limit:
      rateLimit:
        average: 100
        period: 1m
        burst: 50

    # IP whitelist (optional - for admin access)
    admin-whitelist:
      ipWhiteList:
        sourceRange:
          - "127.0.0.1/32"
          - "10.0.0.0/8"
          - "172.16.0.0/12"
          - "192.168.0.0/16"

    # Basic auth for admin endpoints
    admin-auth:
      basicAuth:
        users:
          - "admin:$2y$10$..."  # Replace with actual bcrypt hash

    # Request size limiting
    limit-request-size:
      buffering:
        maxRequestBodyBytes: 1048576  # 1MB limit

    # Compression
    compression:
      compress: {}

    # Circuit breaker
    circuit-breaker:
      circuitBreaker:
        expression: "NetworkErrorRatio() > 0.30"

    # Retry
    retry:
      retry:
        attempts: 3
        initialInterval: 100ms

    # Timeout
    timeout:
      forwardingTimeouts:
        dialTimeout: 30s
        responseHeaderTimeout: 30s
        idleConnTimeout: 90s

# TCP middleware (for WebSocket connections)
tcp:
  middlewares:
    # IP whitelist for WebSocket connections
    websocket-whitelist:
      ipWhiteList:
        sourceRange:
          - "0.0.0.0/0"  # Allow all for WebSocket - adjust as needed