# GitHub MCP Server Configuration
# This file contains default settings that can be overridden by environment variables

[server]
host = "127.0.0.1"
port = 8443
workers = 4
max_connections = 1000

[database]
url = "sqlite:./data/github-mcp-server.db"
max_connections = 10
min_connections = 1
connect_timeout = 30
idle_timeout = 600

[security]
jwt_secret = "change-this-in-production"
rate_limit_requests_per_minute = 60
session_timeout_hours = 24
max_token_age_days = 30
audit_log_enabled = true
password_hash_cost = 12

[github]
client_id = ""
client_secret = ""
redirect_uri = "https://localhost:8443/auth/github/callback"
api_base_url = "https://api.github.com"
api_timeout = 30
max_retries = 3

[logging]
level = "info"
format = "json"
file = "./logs/github-mcp-server.log"
max_file_size = "10MB"
max_files = 5

[cors]
allowed_origins = ["https://localhost:8443"]
allowed_methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
allowed_headers = ["Content-Type", "Authorization", "X-Requested-With"]
max_age = 3600

[tls]
cert_file = "./certs/server.crt"
key_file = "./certs/server.key"
min_version = "1.2"
max_version = "1.3"

[monitoring]
metrics_enabled = true
metrics_port = 9090
health_check_interval = 30
prometheus_namespace = "github_mcp_server"